[package]
name = "encryptor_decryptor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = "0.10.3"
crypto = "0.5.0"
chacha20poly1305 = "0.10.0"
base64 = "0.22.0"
argon2 = "0.5.3"
