[package]
name = "communication"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { version = "2.0", features = ["rustls", "ws"] }
tokio = { version = "1", features = ["macros"] }
eyre = "0.6"

[toolchain]
channel = "nightly"