[package]
name = "communication"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
ethers = { version = "2.0", features = ["rustls", "ws"] }
tokio = { version = "1", features = ["macros"] }
serde_json = "1.0.116"
eyre = "0.6.12"

[toolchain]
channel = "nightly"
