[package]
name = "rest_api_client"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.4"
tokio = { veriosn = "1.36.0", features = ["macros", "rt-multi-thread"] }
serde_json = "1.0.116"
